//! Candle Provider — fully local, native Rust LLM inference
//!
//! Uses Hugging Face Candle for on-device transformer inference with no
//! HTTP calls, no Python, no external servers, and no API keys.
//!
//! # Capabilities
//!
//! | Feature     | Status |
//! |-------------|--------|
//! | Chat        | ✅     |
//! | Streaming   | ✅     |
//! | Tool calls  | ✅     |
//! | Embeddings  | ✅     |
//! | Vision      | ❌     |
//!
//! # Supported model formats
//!
//! - SafeTensors (`.safetensors`)
//! - Auto-detected architectures: Llama, Mistral, Phi, Qwen2
//!
//! # Quick start
//!
//! ```rust,ignore
//! use mofa_foundation::llm::candle::{CandleConfig, CandleProvider};
//!
//! let config = CandleConfig::new("/path/to/model")
//!     .with_model_id("my-local-model")
//!     .with_max_tokens(512);
//!
//! let provider = CandleProvider::load(config).await?;
//! let response = provider.chat(request).await?;
//! ```
//!
//! # Streaming
//!
//! ```rust,ignore
//! use futures::StreamExt;
//!
//! let mut stream = provider.chat_stream(request).await?;
//! while let Some(chunk) = stream.next().await {
//!     match chunk {
//!         Ok(c) => print!("{}", c.choices[0].delta.content.as_deref().unwrap_or("")),
//!         Err(e) => eprintln!("Error: {}", e),
//!     }
//! }
//! ```
//!
//! # Tool calling
//!
//! The provider detects tool call JSON in model output when tools are provided
//! in the request. Models must be instruction-tuned for function calling
//! (e.g. Llama-3.1-Instruct, Mistral-Instruct, Hermes-2-Pro).
//!
//! # Embeddings
//!
//! Embeddings are generated by running a forward pass and mean-pooling the
//! last hidden state. Works best with embedding-specific models, but any
//! transformer model can produce embeddings.
//!
//! # Feature gate
//!
//! This module is only available when the `linux-candle` feature is enabled:
//!
//! ```toml
//! mofa-foundation = { version = "0.1", features = ["linux-candle"] }
//! ```

use super::provider::{ChatStream, LLMProvider, ModelCapabilities, ModelInfo};
use super::types::*;
use async_trait::async_trait;
use candle_core::{DType, Device, Tensor};
use candle_transformers::generation::LogitsProcessor;
use futures::Stream;
use std::path::{Path, PathBuf};
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll};
use tokio::sync::Mutex;

// ============================================================================
// Configuration
// ============================================================================

/// Configuration for the Candle local inference provider.
#[derive(Debug, Clone)]
pub struct CandleConfig {
    /// Path to the model directory (must contain config.json, tokenizer.json,
    /// and model weight files in SafeTensors format).
    pub model_path: PathBuf,

    /// Logical model identifier surfaced via `default_model()` and embedded in
    /// responses. Defaults to the directory name of `model_path`.
    pub model_id: String,

    /// Default temperature for sampling. 0.0 = greedy.
    pub default_temperature: f64,

    /// Default maximum number of tokens to generate.
    pub default_max_tokens: usize,

    /// Top-p (nucleus) sampling threshold. `None` disables it.
    pub top_p: Option<f64>,

    /// Repetition penalty applied to already-generated tokens.
    pub repeat_penalty: f32,

    /// Number of recent tokens considered for the repetition penalty window.
    pub repeat_last_n: usize,

    /// Random seed for reproducibility. `None` uses a random seed.
    pub seed: Option<u64>,

    /// Whether to attempt GPU (CUDA) acceleration.
    pub use_gpu: bool,

    /// Data type for model weights. `None` = auto-detect from model files.
    pub dtype: Option<DType>,

    /// Tool calling format to use when tools are present.
    pub tool_format: ToolCallFormat,

    /// Embedding pooling strategy.
    pub embedding_pooling: EmbeddingPooling,
}

/// Format for tool calling in the prompt.
#[derive(Debug, Clone, Default)]
pub enum ToolCallFormat {
    /// ChatML-style tool format (Hermes-2-Pro, Llama-3.1)
    #[default]
    ChatML,
    /// Raw JSON function call format
    RawJson,
}

/// Pooling strategy for embedding extraction.
#[derive(Debug, Clone, Default)]
pub enum EmbeddingPooling {
    /// Mean of all token hidden states
    #[default]
    Mean,
    /// First token ([CLS] / BOS) hidden state
    FirstToken,
    /// Last token hidden state
    LastToken,
}

impl CandleConfig {
    /// Create a minimal configuration pointing at a local model directory.
    pub fn new(model_path: impl Into<PathBuf>) -> Self {
        let path: PathBuf = model_path.into();
        let model_id = path
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_else(|| "candle-model".to_string());

        Self {
            model_path: path,
            model_id,
            default_temperature: 0.7,
            default_max_tokens: 512,
            top_p: Some(0.9),
            repeat_penalty: 1.1,
            repeat_last_n: 64,
            seed: Some(42),
            use_gpu: false,
            dtype: None,
            tool_format: ToolCallFormat::default(),
            embedding_pooling: EmbeddingPooling::default(),
        }
    }

    pub fn with_model_id(mut self, id: impl Into<String>) -> Self {
        self.model_id = id.into();
        self
    }

    pub fn with_temperature(mut self, temp: f64) -> Self {
        self.default_temperature = temp;
        self
    }

    pub fn with_max_tokens(mut self, tokens: usize) -> Self {
        self.default_max_tokens = tokens;
        self
    }

    pub fn with_top_p(mut self, top_p: f64) -> Self {
        self.top_p = Some(top_p);
        self
    }

    pub fn with_repeat_penalty(mut self, penalty: f32) -> Self {
        self.repeat_penalty = penalty;
        self
    }

    pub fn with_repeat_last_n(mut self, n: usize) -> Self {
        self.repeat_last_n = n;
        self
    }

    pub fn with_seed(mut self, seed: u64) -> Self {
        self.seed = Some(seed);
        self
    }

    pub fn with_gpu(mut self, enabled: bool) -> Self {
        self.use_gpu = enabled;
        self
    }

    pub fn with_dtype(mut self, dtype: DType) -> Self {
        self.dtype = Some(dtype);
        self
    }

    pub fn with_tool_format(mut self, format: ToolCallFormat) -> Self {
        self.tool_format = format;
        self
    }

    pub fn with_embedding_pooling(mut self, pooling: EmbeddingPooling) -> Self {
        self.embedding_pooling = pooling;
        self
    }
}

// ============================================================================
// Tokenizer wrapper
// ============================================================================

/// Thin wrapper around a tokenizer loaded from `tokenizer.json`.
struct TokenizerWrapper {
    inner: tokenizers::Tokenizer,
}

impl TokenizerWrapper {
    fn from_file(path: &Path) -> Result<Self, LLMError> {
        let inner = tokenizers::Tokenizer::from_file(path).map_err(|e| {
            LLMError::ConfigError(format!("Failed to load tokenizer from {:?}: {}", path, e))
        })?;
        Ok(Self { inner })
    }

    fn encode(&self, text: &str) -> Result<Vec<u32>, LLMError> {
        let encoding = self
            .inner
            .encode(text, true)
            .map_err(|e| LLMError::Other(format!("Tokenization failed: {}", e)))?;
        Ok(encoding.get_ids().to_vec())
    }

    fn decode(&self, tokens: &[u32]) -> Result<String, LLMError> {
        self.inner
            .decode(tokens, true)
            .map_err(|e| LLMError::Other(format!("Detokenization failed: {}", e)))
    }

    /// Decode a single token to text (used for streaming).
    fn decode_single(&self, token: u32) -> Result<String, LLMError> {
        self.decode(&[token])
    }

    /// Return the EOS token id, if the tokenizer defines one.
    fn eos_token_id(&self) -> Option<u32> {
        let vocab = self.inner.get_added_vocabulary().get_vocab();
        vocab
            .get("</s>")
            .copied()
            .or_else(|| vocab.get("<|endoftext|>").copied())
            .or_else(|| vocab.get("<|end|>").copied())
            .or_else(|| vocab.get("<|eot_id|>").copied())
    }

    /// Return the vocab size.
    fn vocab_size(&self) -> usize {
        self.inner.get_vocab_size(true)
    }
}

// ============================================================================
// Model architecture abstraction
// ============================================================================

/// Supported model architectures for auto-detection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ModelArch {
    Llama,
    Mistral,
    Phi,
    Qwen2,
}

/// A simple JSON config.json reader that detects the architecture.
fn detect_architecture(model_path: &Path) -> Result<ModelArch, LLMError> {
    let config_path = model_path.join("config.json");
    let config_text = std::fs::read_to_string(&config_path).map_err(|e| {
        LLMError::ConfigError(format!("Cannot read {:?}: {}", config_path, e))
    })?;
    let config: serde_json::Value = serde_json::from_str(&config_text)
        .map_err(|e| LLMError::ConfigError(format!("Invalid config.json: {}", e)))?;

    let arch_str = config
        .get("architectures")
        .and_then(|a| a.as_array())
        .and_then(|a| a.first())
        .and_then(|v| v.as_str())
        .or_else(|| config.get("model_type").and_then(|v| v.as_str()))
        .unwrap_or("");

    let arch_lower = arch_str.to_lowercase();

    if arch_lower.contains("llama") {
        Ok(ModelArch::Llama)
    } else if arch_lower.contains("mistral") {
        Ok(ModelArch::Mistral)
    } else if arch_lower.contains("phi") {
        Ok(ModelArch::Phi)
    } else if arch_lower.contains("qwen2") {
        Ok(ModelArch::Qwen2)
    } else {
        tracing::warn!(
            "Unknown model architecture '{}', falling back to Llama",
            arch_str
        );
        Ok(ModelArch::Llama)
    }
}

/// Read the hidden size from config.json for embedding dimension.
fn read_hidden_size(model_path: &Path) -> Result<usize, LLMError> {
    let config_path = model_path.join("config.json");
    let config_text = std::fs::read_to_string(&config_path).map_err(|e| {
        LLMError::ConfigError(format!("Cannot read {:?}: {}", config_path, e))
    })?;
    let config: serde_json::Value = serde_json::from_str(&config_text)
        .map_err(|e| LLMError::ConfigError(format!("Invalid config.json: {}", e)))?;

    config
        .get("hidden_size")
        .and_then(|v| v.as_u64())
        .map(|v| v as usize)
        .ok_or_else(|| LLMError::ConfigError("hidden_size not found in config.json".to_string()))
}

// ============================================================================
// Inference engine
// ============================================================================

/// Everything needed to run inference. Wrapped in `Arc<Mutex<_>>` inside
/// the provider because Candle model state is not `Sync`.
struct InferenceEngine {
    model: Box<dyn CandleModel>,
    tokenizer: TokenizerWrapper,
    device: Device,
    config: CandleConfig,
    hidden_size: usize,
}

/// Trait that abstracts over different Candle model forward passes.
trait CandleModel: Send {
    /// Run a forward pass and return logits of shape `[1, seq_len, vocab_size]`
    /// or `[1, vocab_size]`.
    fn forward(
        &mut self,
        input_ids: &Tensor,
        position: usize,
    ) -> Result<Tensor, candle_core::Error>;

    /// Run a forward pass and return the last hidden states of shape
    /// `[1, seq_len, hidden_size]` for embedding extraction.
    /// Default implementation returns an error.
    fn forward_hidden(
        &mut self,
        input_ids: &Tensor,
        position: usize,
    ) -> Result<Tensor, candle_core::Error> {
        // Fall back to regular forward — some architectures expose this,
        // others don't. We use the logits forward as a rough approximation
        // when hidden states aren't available.
        let _ = (input_ids, position);
        Err(candle_core::Error::Msg(
            "forward_hidden not implemented for this architecture".to_string(),
        ))
    }

    /// Reset any KV-cache between requests.
    fn reset(&mut self);
}

// ---------------------------------------------------------------------------
// Llama implementation
// ---------------------------------------------------------------------------

struct LlamaModel {
    model: candle_transformers::models::llama::Llama,
    cache: candle_transformers::models::llama::Cache,
}

impl CandleModel for LlamaModel {
    fn forward(
        &mut self,
        input_ids: &Tensor,
        position: usize,
    ) -> Result<Tensor, candle_core::Error> {
        self.model.forward(input_ids, position, &mut self.cache)
    }

    fn reset(&mut self) {
        self.cache.clear();
    }
}

// ---------------------------------------------------------------------------
// Model loading
// ---------------------------------------------------------------------------

/// Find all SafeTensors weight files in a directory.
fn find_safetensor_files(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .map(|ext| ext == "safetensors")
                .unwrap_or(false)
        })
        .collect();
    files.sort();
    files
}

fn load_model(
    arch: ModelArch,
    model_path: &Path,
    device: &Device,
    dtype: DType,
) -> Result<Box<dyn CandleModel>, LLMError> {
    let config_path = model_path.join("config.json");
    let config_text = std::fs::read_to_string(&config_path)
        .map_err(|e| LLMError::ConfigError(format!("Cannot read config.json: {}", e)))?;

    let weight_files = find_safetensor_files(model_path);
    if weight_files.is_empty() {
        return Err(LLMError::ConfigError(format!(
            "No .safetensors files found in {:?}",
            model_path
        )));
    }

    let vb = unsafe {
        candle_core::safetensors::MmapedSafetensors::multi(&weight_files)
            .map_err(|e| LLMError::ConfigError(format!("Failed to mmap weights: {}", e)))?
    };
    let vb =
        candle_core::nn::VarBuilder::from_mmaped_safetensors(vec![vb], dtype, device)
            .map_err(|e| LLMError::ConfigError(format!("VarBuilder error: {}", e)))?;

    match arch {
        ModelArch::Llama | ModelArch::Mistral | ModelArch::Phi | ModelArch::Qwen2 => {
            if !matches!(arch, ModelArch::Llama) {
                tracing::info!(
                    "Architecture {:?} using Llama-compatible loader",
                    arch
                );
            }

            let llama_config: candle_transformers::models::llama::LlamaConfig =
                serde_json::from_str(&config_text).map_err(|e| {
                    LLMError::ConfigError(format!("Invalid Llama config: {}", e))
                })?;
            // use_flash_attn = false for maximum compatibility
            let config = llama_config.into_config(false);
            let cache = candle_transformers::models::llama::Cache::new(
                true, dtype, &config, device,
            )
            .map_err(|e| LLMError::ConfigError(format!("Cache init failed: {}", e)))?;
            let model = candle_transformers::models::llama::Llama::load(vb, &config)
                .map_err(|e| LLMError::ConfigError(format!("Model load failed: {}", e)))?;
            Ok(Box::new(LlamaModel { model, cache }))
        }
    }
}

// ============================================================================
// Prompt formatting
// ============================================================================

/// Convert MoFA `ChatMessage` list into a single prompt string.
///
/// Uses ChatML format that works with most instruction-tuned models
/// (Llama-3, Mistral-Instruct, Phi-3, Qwen-2, Hermes-2-Pro, etc.):
///
/// ```text
/// <|im_start|>system
/// You are helpful.<|im_end|>
/// <|im_start|>user
/// Hello<|im_end|>
/// <|im_start|>assistant
/// ```
fn format_prompt(messages: &[ChatMessage], tools: Option<&[Tool]>) -> String {
    let mut prompt = String::new();

    // If tools are provided, inject them into the system message
    if let Some(tools) = tools {
        if !tools.is_empty() {
            prompt.push_str("<|im_start|>system\n");
            // Find existing system message content
            let system_content: String = messages
                .iter()
                .filter(|m| m.role == Role::System)
                .filter_map(|m| m.text_content())
                .collect::<Vec<_>>()
                .join("\n");

            if !system_content.is_empty() {
                prompt.push_str(&system_content);
                prompt.push_str("\n\n");
            }

            prompt.push_str("You have access to the following tools:\n\n");
            for tool in tools {
                let tool_json = serde_json::json!({
                    "type": "function",
                    "function": {
                        "name": tool.function.name,
                        "description": tool.function.description,
                        "parameters": tool.function.parameters,
                    }
                });
                prompt.push_str(&serde_json::to_string_pretty(&tool_json).unwrap_or_default());
                prompt.push('\n');
            }
            prompt.push_str("\nTo call a tool, respond with a JSON object in this exact format:\n");
            prompt.push_str(r#"{"tool_calls": [{"id": "call_<unique_id>", "type": "function", "function": {"name": "<tool_name>", "arguments": "<json_arguments>"}}]}"#);
            prompt.push_str("\n\nIf you don't need to call a tool, respond normally with text.\n");
            prompt.push_str("<|im_end|>\n");

            // Now add non-system messages
            for msg in messages {
                if msg.role == Role::System {
                    continue; // Already handled above
                }
                let role = match msg.role {
                    Role::User => "user",
                    Role::Assistant => "assistant",
                    Role::Tool => "tool",
                    Role::System => unreachable!(),
                };
                let content = msg.text_content().unwrap_or("");
                prompt.push_str(&format!(
                    "<|im_start|>{}\n{}<|im_end|>\n",
                    role, content
                ));
            }
        } else {
            // No tools, format normally
            format_messages_chatml(&mut prompt, messages);
        }
    } else {
        format_messages_chatml(&mut prompt, messages);
    }

    // Open the assistant turn for generation
    prompt.push_str("<|im_start|>assistant\n");
    prompt
}

/// Format messages in standard ChatML without tool definitions.
fn format_messages_chatml(prompt: &mut String, messages: &[ChatMessage]) {
    for msg in messages {
        let role = match msg.role {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
        };
        let content = msg.text_content().unwrap_or("");
        prompt.push_str(&format!(
            "<|im_start|>{}\n{}<|im_end|>\n",
            role, content
        ));
    }
}

// ============================================================================
// Tool call parsing
// ============================================================================

/// Attempt to parse tool calls from generated text.
///
/// Supports two formats:
/// 1. `{"tool_calls": [{"id": "...", "type": "function", "function": {...}}]}`
/// 2. `{"name": "...", "arguments": {...}}` (simpler format some models use)
fn parse_tool_calls(text: &str) -> Option<Vec<ToolCall>> {
    let trimmed = text.trim();

    // Try to find JSON in the text (model might wrap it in markdown or other text)
    let json_str = extract_json_block(trimmed)?;

    // Attempt format 1: full tool_calls array
    if let Ok(parsed) = serde_json::from_str::<serde_json::Value>(json_str) {
        if let Some(tool_calls) = parsed.get("tool_calls").and_then(|v| v.as_array()) {
            let calls: Vec<ToolCall> = tool_calls
                .iter()
                .filter_map(|tc| {
                    let id = tc
                        .get("id")
                        .and_then(|v| v.as_str())
                        .unwrap_or("call_0")
                        .to_string();
                    let func = tc.get("function")?;
                    let name = func.get("name")?.as_str()?.to_string();
                    let arguments = func.get("arguments").map(|a| {
                        if a.is_string() {
                            a.as_str().unwrap_or("{}").to_string()
                        } else {
                            a.to_string()
                        }
                    }).unwrap_or_else(|| "{}".to_string());

                    Some(ToolCall {
                        id,
                        call_type: "function".to_string(),
                        function: FunctionCall { name, arguments },
                    })
                })
                .collect();

            if !calls.is_empty() {
                return Some(calls);
            }
        }

        // Attempt format 2: single function call
        if let (Some(name), Some(arguments)) = (
            parsed.get("name").and_then(|v| v.as_str()),
            parsed.get("arguments"),
        ) {
            let arguments_str = if arguments.is_string() {
                arguments.as_str().unwrap_or("{}").to_string()
            } else {
                arguments.to_string()
            };

            return Some(vec![ToolCall {
                id: format!("call_{}", uuid::Uuid::now_v7()),
                call_type: "function".to_string(),
                function: FunctionCall {
                    name: name.to_string(),
                    arguments: arguments_str,
                },
            }]);
        }
    }

    None
}

/// Extract a JSON block from text that may contain surrounding prose.
fn extract_json_block(text: &str) -> Option<&str> {
    // Look for ```json ... ``` code block first
    if let Some(start) = text.find("```json") {
        let json_start = start + 7;
        if let Some(end) = text[json_start..].find("```") {
            return Some(text[json_start..json_start + end].trim());
        }
    }

    // Look for ``` ... ``` code block
    if let Some(start) = text.find("```") {
        let code_start = start + 3;
        // Skip optional language identifier on the same line
        let content_start = text[code_start..]
            .find('\n')
            .map(|i| code_start + i + 1)
            .unwrap_or(code_start);
        if let Some(end) = text[content_start..].find("```") {
            return Some(text[content_start..content_start + end].trim());
        }
    }

    // Try to find a top-level JSON object in the text
    let first_brace = text.find('{')?;
    let mut depth = 0i32;
    let mut last_brace = first_brace;

    for (i, ch) in text[first_brace..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    last_brace = first_brace + i;
                    break;
                }
            }
            _ => {}
        }
    }

    if depth == 0 && last_brace > first_brace {
        Some(&text[first_brace..=last_brace])
    } else {
        None
    }
}

// ============================================================================
// Generation loop
// ============================================================================

/// Result of a generation run.
struct GenerationResult {
    /// Generated token ids (not including prompt).
    tokens: Vec<u32>,
    /// Decoded text.
    text: String,
    /// Number of prompt tokens.
    prompt_token_count: u32,
    /// Number of generated tokens.
    completion_token_count: u32,
    /// Why generation stopped.
    finish_reason: FinishReason,
    /// Parsed tool calls, if any.
    tool_calls: Option<Vec<ToolCall>>,
}

/// Run the autoregressive generation loop.
fn generate_sync(
    engine: &mut InferenceEngine,
    prompt_tokens: &[u32],
    max_new_tokens: usize,
    temperature: f64,
    top_p: Option<f64>,
    repeat_penalty: f32,
    repeat_last_n: usize,
    seed: u64,
    has_tools: bool,
) -> Result<GenerationResult, LLMError> {
    let map_err = |e: candle_core::Error| LLMError::Other(format!("Candle error: {}", e));

    engine.model.reset();

    let eos_token = engine.tokenizer.eos_token_id();
    let im_end_token = engine
        .tokenizer
        .encode("<|im_end|>")
        .ok()
        .and_then(|ids| ids.last().copied());

    let mut logits_processor = LogitsProcessor::new(seed, Some(temperature), top_p);

    let prompt_len = prompt_tokens.len() as u32;
    let mut all_tokens: Vec<u32> = prompt_tokens.to_vec();
    let mut generated_tokens: Vec<u32> = Vec::with_capacity(max_new_tokens);

    // Prefill: process the entire prompt
    let input = Tensor::new(prompt_tokens, &engine.device).map_err(map_err)?;
    let input = input.unsqueeze(0).map_err(map_err)?;
    let logits = engine.model.forward(&input, 0).map_err(map_err)?;

    // Sample first token from last position
    let logits = logits
        .squeeze(0)
        .map_err(map_err)?
        .to_dtype(DType::F32)
        .map_err(map_err)?;
    // If logits is [seq_len, vocab], take the last position
    let logits = if logits.dims().len() == 2 {
        let seq_len = logits.dim(0).map_err(map_err)?;
        logits
            .narrow(0, seq_len - 1, 1)
            .map_err(map_err)?
            .squeeze(0)
            .map_err(map_err)?
    } else {
        logits
    };
    let logits =
        apply_repeat_penalty(&logits, &all_tokens, repeat_penalty, repeat_last_n)?;
    let mut next_token = logits_processor.sample(&logits).map_err(map_err)?;

    generated_tokens.push(next_token);
    all_tokens.push(next_token);

    if is_stop_token(next_token, eos_token, im_end_token) {
        let text = decode_and_clean(&engine.tokenizer, &generated_tokens)?;
        let tool_calls = if has_tools { parse_tool_calls(&text) } else { None };
        let finish_reason = if tool_calls.is_some() {
            FinishReason::ToolCalls
        } else {
            FinishReason::Stop
        };
        return Ok(GenerationResult {
            tokens: generated_tokens,
            text,
            prompt_token_count: prompt_len,
            completion_token_count: 1,
            finish_reason,
            tool_calls,
        });
    }

    // Autoregressive decode loop
    for i in 1..max_new_tokens {
        let input = Tensor::new(&[next_token], &engine.device).map_err(map_err)?;
        let input = input.unsqueeze(0).map_err(map_err)?;
        let logits = engine
            .model
            .forward(&input, prompt_tokens.len() + i)
            .map_err(map_err)?;

        let logits = logits
            .squeeze(0)
            .map_err(map_err)?
            .to_dtype(DType::F32)
            .map_err(map_err)?;
        // Handle [1, vocab] shape from single-token input
        let logits = if logits.dims().len() == 2 {
            logits.squeeze(0).map_err(map_err)?
        } else {
            logits
        };
        let logits =
            apply_repeat_penalty(&logits, &all_tokens, repeat_penalty, repeat_last_n)?;
        next_token = logits_processor.sample(&logits).map_err(map_err)?;

        generated_tokens.push(next_token);
        all_tokens.push(next_token);

        if is_stop_token(next_token, eos_token, im_end_token) {
            break;
        }
    }

    let completion_count = generated_tokens.len() as u32;
    let finish_reason = if (completion_count as usize) >= max_new_tokens {
        FinishReason::Length
    } else {
        FinishReason::Stop
    };

    let text = decode_and_clean(&engine.tokenizer, &generated_tokens)?;

    let tool_calls = if has_tools { parse_tool_calls(&text) } else { None };
    let finish_reason = if tool_calls.is_some() {
        FinishReason::ToolCalls
    } else {
        finish_reason
    };

    Ok(GenerationResult {
        tokens: generated_tokens,
        text,
        prompt_token_count: prompt_len,
        completion_token_count: completion_count,
        finish_reason,
        tool_calls,
    })
}

/// Streaming generation: sends each token through a channel as it's produced.
fn generate_streaming(
    engine: &mut InferenceEngine,
    prompt_tokens: &[u32],
    max_new_tokens: usize,
    temperature: f64,
    top_p: Option<f64>,
    repeat_penalty: f32,
    repeat_last_n: usize,
    seed: u64,
    model_id: String,
    tx: tokio::sync::mpsc::Sender<LLMResult<ChatCompletionChunk>>,
) {
    let result = generate_streaming_inner(
        engine,
        prompt_tokens,
        max_new_tokens,
        temperature,
        top_p,
        repeat_penalty,
        repeat_last_n,
        seed,
        &model_id,
        &tx,
    );

    if let Err(e) = result {
        let _ = tx.blocking_send(Err(e));
    }
}

fn generate_streaming_inner(
    engine: &mut InferenceEngine,
    prompt_tokens: &[u32],
    max_new_tokens: usize,
    temperature: f64,
    top_p: Option<f64>,
    repeat_penalty: f32,
    repeat_last_n: usize,
    seed: u64,
    model_id: &str,
    tx: &tokio::sync::mpsc::Sender<LLMResult<ChatCompletionChunk>>,
) -> Result<(), LLMError> {
    let map_err = |e: candle_core::Error| LLMError::Other(format!("Candle error: {}", e));

    engine.model.reset();

    let eos_token = engine.tokenizer.eos_token_id();
    let im_end_token = engine
        .tokenizer
        .encode("<|im_end|>")
        .ok()
        .and_then(|ids| ids.last().copied());

    let mut logits_processor = LogitsProcessor::new(seed, Some(temperature), top_p);

    let mut all_tokens: Vec<u32> = prompt_tokens.to_vec();

    let now_secs = || -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
    };

    let chunk_id = format!("candle-stream-{}", uuid::Uuid::now_v7());

    // Send initial chunk with role
    let initial_chunk = ChatCompletionChunk {
        id: chunk_id.clone(),
        object: "chat.completion.chunk".to_string(),
        created: now_secs(),
        model: model_id.to_string(),
        choices: vec![ChunkChoice {
            index: 0,
            delta: ChunkDelta {
                role: Some(Role::Assistant),
                content: None,
                tool_calls: None,
            },
            finish_reason: None,
        }],
        usage: None,
    };
    if tx.blocking_send(Ok(initial_chunk)).is_err() {
        return Ok(()); // Receiver dropped
    }

    // Prefill
    let input = Tensor::new(prompt_tokens, &engine.device).map_err(map_err)?;
    let input = input.unsqueeze(0).map_err(map_err)?;
    let logits = engine.model.forward(&input, 0).map_err(map_err)?;

    let logits = logits
        .squeeze(0)
        .map_err(map_err)?
        .to_dtype(DType::F32)
        .map_err(map_err)?;
    let logits = if logits.dims().len() == 2 {
        let seq_len = logits.dim(0).map_err(map_err)?;
        logits
            .narrow(0, seq_len - 1, 1)
            .map_err(map_err)?
            .squeeze(0)
            .map_err(map_err)?
    } else {
        logits
    };
    let logits =
        apply_repeat_penalty(&logits, &all_tokens, repeat_penalty, repeat_last_n)?;
    let mut next_token = logits_processor.sample(&logits).map_err(map_err)?;

    all_tokens.push(next_token);

    if is_stop_token(next_token, eos_token, im_end_token) {
        send_final_chunk(tx, &chunk_id, model_id, now_secs(), FinishReason::Stop);
        return Ok(());
    }

    // Send first token
    let token_text = engine.tokenizer.decode_single(next_token)?;
    let token_text = clean_streaming_token(&token_text);
    if !token_text.is_empty() {
        send_content_chunk(tx, &chunk_id, model_id, now_secs(), &token_text);
    }

    // Autoregressive decode loop
    for i in 1..max_new_tokens {
        let input = Tensor::new(&[next_token], &engine.device).map_err(map_err)?;
        let input = input.unsqueeze(0).map_err(map_err)?;
        let logits = engine
            .model
            .forward(&input, prompt_tokens.len() + i)
            .map_err(map_err)?;

        let logits = logits
            .squeeze(0)
            .map_err(map_err)?
            .to_dtype(DType::F32)
            .map_err(map_err)?;
        let logits = if logits.dims().len() == 2 {
            logits.squeeze(0).map_err(map_err)?
        } else {
            logits
        };
        let logits =
            apply_repeat_penalty(&logits, &all_tokens, repeat_penalty, repeat_last_n)?;
        next_token = logits_processor.sample(&logits).map_err(map_err)?;
        all_tokens.push(next_token);

        if is_stop_token(next_token, eos_token, im_end_token) {
            send_final_chunk(tx, &chunk_id, model_id, now_secs(), FinishReason::Stop);
            return Ok(());
        }

        let token_text = engine.tokenizer.decode_single(next_token)?;
        let token_text = clean_streaming_token(&token_text);
        if !token_text.is_empty() {
            if tx
                .blocking_send(Ok(ChatCompletionChunk {
                    id: chunk_id.clone(),
                    object: "chat.completion.chunk".to_string(),
                    created: now_secs(),
                    model: model_id.to_string(),
                    choices: vec![ChunkChoice {
                        index: 0,
                        delta: ChunkDelta {
                            role: None,
                            content: Some(token_text),
                            tool_calls: None,
                        },
                        finish_reason: None,
                    }],
                    usage: None,
                }))
                .is_err()
            {
                return Ok(()); // Receiver dropped
            }
        }
    }

    // Max tokens reached
    send_final_chunk(tx, &chunk_id, model_id, now_secs(), FinishReason::Length);
    Ok(())
}

fn send_content_chunk(
    tx: &tokio::sync::mpsc::Sender<LLMResult<ChatCompletionChunk>>,
    id: &str,
    model: &str,
    created: u64,
    content: &str,
) {
    let _ = tx.blocking_send(Ok(ChatCompletionChunk {
        id: id.to_string(),
        object: "chat.completion.chunk".to_string(),
        created,
        model: model.to_string(),
        choices: vec![ChunkChoice {
            index: 0,
            delta: ChunkDelta {
                role: None,
                content: Some(content.to_string()),
                tool_calls: None,
            },
            finish_reason: None,
        }],
        usage: None,
    }));
}

fn send_final_chunk(
    tx: &tokio::sync::mpsc::Sender<LLMResult<ChatCompletionChunk>>,
    id: &str,
    model: &str,
    created: u64,
    reason: FinishReason,
) {
    let _ = tx.blocking_send(Ok(ChatCompletionChunk {
        id: id.to_string(),
        object: "chat.completion.chunk".to_string(),
        created,
        model: model.to_string(),
        choices: vec![ChunkChoice {
            index: 0,
            delta: ChunkDelta {
                role: None,
                content: None,
                tool_calls: None,
            },
            finish_reason: Some(reason),
        }],
        usage: None,
    }));
}

/// Clean streaming tokens of ChatML artifacts.
fn clean_streaming_token(token: &str) -> String {
    if token.contains("<|im_end|>")
        || token.contains("<|endoftext|>")
        || token.contains("</s>")
        || token.contains("<|im_start|>")
    {
        String::new()
    } else {
        token.to_string()
    }
}

fn is_stop_token(token: u32, eos: Option<u32>, im_end: Option<u32>) -> bool {
    if let Some(eos_id) = eos {
        if token == eos_id {
            return true;
        }
    }
    if let Some(im_end_id) = im_end {
        if token == im_end_id {
            return true;
        }
    }
    false
}

fn apply_repeat_penalty(
    logits: &Tensor,
    all_tokens: &[u32],
    penalty: f32,
    last_n: usize,
) -> Result<Tensor, LLMError> {
    if penalty <= 1.0 || last_n == 0 || all_tokens.is_empty() {
        return Ok(logits.clone());
    }

    let map_err = |e: candle_core::Error| LLMError::Other(format!("Penalty error: {}", e));

    let start = all_tokens.len().saturating_sub(last_n);
    let penalty_tokens = &all_tokens[start..];

    candle_transformers::utils::apply_repeat_penalty(logits, penalty, penalty_tokens)
        .map_err(map_err)
}

/// Decode tokens and clean up ChatML artifacts.
fn decode_and_clean(tokenizer: &TokenizerWrapper, tokens: &[u32]) -> Result<String, LLMError> {
    let text = tokenizer.decode(tokens)?;
    Ok(text
        .trim()
        .trim_end_matches("<|im_end|>")
        .trim_end_matches("<|endoftext|>")
        .trim_end_matches("</s>")
        .trim_end_matches("<|eot_id|>")
        .trim()
        .to_string())
}

// ============================================================================
// Embedding extraction
// ============================================================================

/// Extract embeddings by running a forward pass and pooling hidden states.
fn extract_embeddings_sync(
    engine: &mut InferenceEngine,
    texts: &[String],
    pooling: &EmbeddingPooling,
) -> Result<Vec<Vec<f32>>, LLMError> {
    let map_err = |e: candle_core::Error| LLMError::Other(format!("Candle error: {}", e));

    let mut embeddings = Vec::with_capacity(texts.len());

    for text in texts {
        engine.model.reset();

        let tokens = engine.tokenizer.encode(text)?;
        if tokens.is_empty() {
            // Return zero vector for empty input
            embeddings.push(vec![0.0f32; engine.hidden_size]);
            continue;
        }

        let input = Tensor::new(&tokens[..], &engine.device).map_err(map_err)?;
        let input = input.unsqueeze(0).map_err(map_err)?;

        // Try to get hidden states; fall back to logits-based approximation
        let hidden = match engine.model.forward_hidden(&input, 0) {
            Ok(h) => h,
            Err(_) => {
                // Use the logits output as a proxy — this is a rough approximation
                // but works for basic similarity tasks
                let logits = engine.model.forward(&input, 0).map_err(map_err)?;
                logits
            }
        };

        // hidden shape: [1, seq_len, hidden_size] or [1, seq_len, vocab_size]
        let hidden = hidden.squeeze(0).map_err(map_err)?; // [seq_len, dim]
        let seq_len = hidden.dim(0).map_err(map_err)?;

        let pooled = match pooling {
            EmbeddingPooling::Mean => {
                hidden
                    .sum(0)
                    .map_err(map_err)?
                    .to_dtype(DType::F32)
                    .map_err(map_err)?
                    .affine(1.0 / seq_len as f64, 0.0)
                    .map_err(map_err)?
            }
            EmbeddingPooling::FirstToken => {
                hidden
                    .get(0)
                    .map_err(map_err)?
                    .to_dtype(DType::F32)
                    .map_err(map_err)?
            }
            EmbeddingPooling::LastToken => {
                hidden
                    .get(seq_len - 1)
                    .map_err(map_err)?
                    .to_dtype(DType::F32)
                    .map_err(map_err)?
            }
        };

        // L2 normalize
        let norm = pooled
            .sqr()
            .map_err(map_err)?
            .sum_all()
            .map_err(map_err)?
            .sqrt()
            .map_err(map_err)?
            .to_scalar::<f32>()
            .map_err(map_err)?;

        let normalized = if norm > 0.0 {
            pooled.affine(1.0 / norm as f64, 0.0).map_err(map_err)?
        } else {
            pooled
        };

        let embedding: Vec<f32> = normalized.to_vec1().map_err(map_err)?;
        embeddings.push(embedding);
    }

    Ok(embeddings)
}

// ============================================================================
// Stream wrapper
// ============================================================================

/// Wraps an `mpsc::Receiver` as a `futures::Stream` for `ChatStream`.
struct ChannelStream {
    rx: tokio::sync::mpsc::Receiver<LLMResult<ChatCompletionChunk>>,
}

impl Stream for ChannelStream {
    type Item = LLMResult<ChatCompletionChunk>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.rx.poll_recv(cx)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        (0, None)
    }
}

// ============================================================================
// CandleProvider
// ============================================================================

/// Local LLM inference provider powered by Hugging Face Candle.
///
/// Runs transformer models entirely on-device (CPU or CUDA GPU) with zero
/// external dependencies — no HTTP, no Python, no API keys.
pub struct CandleProvider {
    engine: Arc<Mutex<InferenceEngine>>,
    config: CandleConfig,
    model_loaded: bool,
}

impl CandleProvider {
    /// Load a model and create a ready-to-use provider.
    ///
    /// This is an async function that internally spawns a blocking task for
    /// the potentially slow model-loading I/O.
    pub async fn load(config: CandleConfig) -> LLMResult<Self> {
        let cfg = config.clone();

        let engine = tokio::task::spawn_blocking(move || -> LLMResult<InferenceEngine> {
            let device = if cfg.use_gpu {
                Device::new_cuda(0).unwrap_or_else(|e| {
                    tracing::warn!("CUDA not available ({}), falling back to CPU", e);
                    Device::Cpu
                })
            } else {
                Device::Cpu
            };

            let dtype = cfg.dtype.unwrap_or(DType::F32);

            tracing::info!(
                "Loading Candle model from {:?} (device={:?}, dtype={:?})",
                cfg.model_path,
                device,
                dtype
            );

            let arch = detect_architecture(&cfg.model_path)?;
            tracing::info!("Detected architecture: {:?}", arch);

            let hidden_size = read_hidden_size(&cfg.model_path).unwrap_or(4096);
            tracing::info!("Hidden size: {}", hidden_size);

            let tokenizer_path = cfg.model_path.join("tokenizer.json");
            let tokenizer = TokenizerWrapper::from_file(&tokenizer_path)?;

            let model = load_model(arch, &cfg.model_path, &device, dtype)?;

            tracing::info!("Candle model loaded successfully");

            Ok(InferenceEngine {
                model,
                tokenizer,
                device,
                config: cfg,
                hidden_size,
            })
        })
        .await
        .map_err(|e| LLMError::Other(format!("Model loading task panicked: {}", e)))??;

        Ok(Self {
            engine: Arc::new(Mutex::new(engine)),
            config,
            model_loaded: true,
        })
    }

    /// Build a `ChatCompletionResponse` from a generation result.
    fn build_response(&self, result: GenerationResult) -> ChatCompletionResponse {
        let created = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        let message = if let Some(tool_calls) = result.tool_calls {
            ChatMessage::assistant_with_tool_calls(tool_calls)
        } else {
            ChatMessage::assistant(result.text)
        };

        ChatCompletionResponse {
            id: format!("candle-{}", uuid::Uuid::now_v7()),
            object: "chat.completion".to_string(),
            created,
            model: self.config.model_id.clone(),
            choices: vec![Choice {
                index: 0,
                message,
                finish_reason: Some(result.finish_reason),
                logprobs: None,
            }],
            usage: Some(Usage {
                prompt_tokens: result.prompt_token_count,
                completion_tokens: result.completion_token_count,
                total_tokens: result.prompt_token_count + result.completion_token_count,
            }),
            system_fingerprint: None,
        }
    }
}

#[async_trait]
impl LLMProvider for CandleProvider {
    fn name(&self) -> &str {
        "candle"
    }

    fn default_model(&self) -> &str {
        &self.config.model_id
    }

    fn supported_models(&self) -> Vec<&str> {
        vec![&self.config.model_id]
    }

    fn supports_streaming(&self) -> bool {
        true
    }

    fn supports_tools(&self) -> bool {
        true
    }

    fn supports_vision(&self) -> bool {
        false
    }

    fn supports_embedding(&self) -> bool {
        true
    }

    async fn chat(&self, request: ChatCompletionRequest) -> LLMResult<ChatCompletionResponse> {
        let temperature = request
            .temperature
            .map(|t| t as f64)
            .unwrap_or(self.config.default_temperature);

        let max_tokens = request
            .max_tokens
            .map(|t| t as usize)
            .unwrap_or(self.config.default_max_tokens);

        let top_p = self.config.top_p;
        let repeat_penalty = self.config.repeat_penalty;
        let repeat_last_n = self.config.repeat_last_n;
        let seed = self.config.seed.unwrap_or(42);

        let has_tools = request
            .tools
            .as_ref()
            .map(|t| !t.is_empty())
            .unwrap_or(false);

        // Format messages into prompt
        let prompt = format_prompt(
            &request.messages,
            request.tools.as_deref(),
        );

        // Run inference on a blocking thread
        let engine = self.engine.clone();
        let result = tokio::task::spawn_blocking(move || -> LLMResult<GenerationResult> {
            let mut engine_guard = engine.blocking_lock();
            let prompt_tokens = engine_guard.tokenizer.encode(&prompt)?;

            generate_sync(
                &mut engine_guard,
                &prompt_tokens,
                max_tokens,
                temperature,
                top_p,
                repeat_penalty,
                repeat_last_n,
                seed,
                has_tools,
            )
        })
        .await
        .map_err(|e| LLMError::Other(format!("Inference task panicked: {}", e)))??;

        Ok(self.build_response(result))
    }

    async fn chat_stream(&self, request: ChatCompletionRequest) -> LLMResult<ChatStream> {
        let temperature = request
            .temperature
            .map(|t| t as f64)
            .unwrap_or(self.config.default_temperature);

        let max_tokens = request
            .max_tokens
            .map(|t| t as usize)
            .unwrap_or(self.config.default_max_tokens);

        let top_p = self.config.top_p;
        let repeat_penalty = self.config.repeat_penalty;
        let repeat_last_n = self.config.repeat_last_n;
        let seed = self.config.seed.unwrap_or(42);
        let model_id = self.config.model_id.clone();

        let prompt = format_prompt(&request.messages, request.tools.as_deref());

        // Channel for streaming tokens from blocking thread to async stream
        let (tx, rx) = tokio::sync::mpsc::channel::<LLMResult<ChatCompletionChunk>>(64);

        let engine = self.engine.clone();

        tokio::task::spawn_blocking(move || {
            let mut engine_guard = engine.blocking_lock();
            let prompt_tokens = match engine_guard.tokenizer.encode(&prompt) {
                Ok(t) => t,
                Err(e) => {
                    let _ = tx.blocking_send(Err(e));
                    return;
                }
            };

            generate_streaming(
                &mut engine_guard,
                &prompt_tokens,
                max_tokens,
                temperature,
                top_p,
                repeat_penalty,
                repeat_last_n,
                seed,
                model_id,
                tx,
            );
        });

        Ok(Box::pin(ChannelStream { rx }))
    }

    async fn embedding(&self, request: EmbeddingRequest) -> LLMResult<EmbeddingResponse> {
        let texts: Vec<String> = match request.input {
            EmbeddingInput::Single(s) => vec![s],
            EmbeddingInput::Multiple(v) => v,
        };

        let pooling = self.config.embedding_pooling.clone();
        let engine = self.engine.clone();
        let model_id = self.config.model_id.clone();

        let embeddings = tokio::task::spawn_blocking(move || -> LLMResult<Vec<Vec<f32>>> {
            let mut engine_guard = engine.blocking_lock();
            extract_embeddings_sync(&mut engine_guard, &texts, &pooling)
        })
        .await
        .map_err(|e| LLMError::Other(format!("Embedding task panicked: {}", e)))??;

        let data: Vec<EmbeddingData> = embeddings
            .into_iter()
            .enumerate()
            .map(|(i, embedding)| EmbeddingData {
                object: "embedding".to_string(),
                index: i as u32,
                embedding,
            })
            .collect();

        let total_tokens = texts.len() as u32; // approximate

        Ok(EmbeddingResponse {
            object: "list".to_string(),
            model: model_id,
            data,
            usage: EmbeddingUsage {
                prompt_tokens: total_tokens,
                total_tokens,
            },
        })
    }

    async fn health_check(&self) -> LLMResult<bool> {
        if !self.model_loaded {
            return Ok(false);
        }

        // Verify we can acquire the engine lock and the device is available
        let engine = self.engine.clone();
        let ok = tokio::task::spawn_blocking(move || -> bool {
            let guard = engine.blocking_lock();
            // Try a trivial tensor operation to verify device health
            match Tensor::zeros((1,), DType::F32, &guard.device) {
                Ok(_) => true,
                Err(e) => {
                    tracing::error!("Candle health check failed: {}", e);
                    false
                }
            }
        })
        .await
        .unwrap_or(false);

        Ok(ok)
    }

    async fn get_model_info(&self, _model: &str) -> LLMResult<ModelInfo> {
        Ok(ModelInfo {
            id: self.config.model_id.clone(),
            name: self.config.model_id.clone(),
            description: Some(format!(
                "Local Candle model loaded from {:?}",
                self.config.model_path
            )),
            context_window: None,
            max_output_tokens: Some(self.config.default_max_tokens as u32),
            training_cutoff: None,
            capabilities: ModelCapabilities {
                streaming: true,
                tools: true,
                vision: false,
                json_mode: false,
                json_schema: false,
            },
        })
    }
}

// ============================================================================
// Convenience constructors
// ============================================================================

/// Create a `CandleProvider` from a local model directory.
///
/// # Example
///
/// ```rust,ignore
/// let provider = candle_from_path("/models/TinyLlama-1.1B-Chat").await?;
/// ```
pub async fn candle_from_path(path: impl Into<PathBuf>) -> LLMResult<CandleProvider> {
    CandleProvider::load(CandleConfig::new(path)).await
}

/// Create a `CandleProvider` from a path with GPU enabled.
///
/// Falls back to CPU if CUDA is not available.
pub async fn candle_from_path_gpu(path: impl Into<PathBuf>) -> LLMResult<CandleProvider> {
    CandleProvider::load(CandleConfig::new(path).with_gpu(true)).await
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ---- Config tests ----

    #[test]
    fn config_defaults() {
        let config = CandleConfig::new("/tmp/test-model");
        assert_eq!(config.model_id, "test-model");
        assert_eq!(config.default_max_tokens, 512);
        assert!((config.default_temperature - 0.7).abs() < f64::EPSILON);
        assert!(!config.use_gpu);
        assert!((config.repeat_penalty - 1.1).abs() < f32::EPSILON);
        assert_eq!(config.repeat_last_n, 64);
        assert_eq!(config.seed, Some(42));
    }

    #[test]
    fn config_builder_chain() {
        let config = CandleConfig::new("/models/llama")
            .with_model_id("my-llama")
            .with_temperature(0.3)
            .with_max_tokens(1024)
            .with_gpu(true)
            .with_seed(123)
            .with_repeat_penalty(1.2)
            .with_repeat_last_n(128)
            .with_top_p(0.95)
            .with_dtype(DType::BF16)
            .with_tool_format(ToolCallFormat::RawJson)
            .with_embedding_pooling(EmbeddingPooling::FirstToken);

        assert_eq!(config.model_id, "my-llama");
        assert_eq!(config.default_max_tokens, 1024);
        assert!((config.default_temperature - 0.3).abs() < f64::EPSILON);
        assert!(config.use_gpu);
        assert_eq!(config.seed, Some(123));
        assert!((config.repeat_penalty - 1.2).abs() < f32::EPSILON);
        assert_eq!(config.repeat_last_n, 128);
        assert_eq!(config.top_p, Some(0.95));
        assert!(matches!(config.tool_format, ToolCallFormat::RawJson));
        assert!(matches!(config.embedding_pooling, EmbeddingPooling::FirstToken));
    }

    #[test]
    fn config_model_id_from_path() {
        let config = CandleConfig::new("/data/models/TinyLlama-1.1B-Chat");
        assert_eq!(config.model_id, "TinyLlama-1.1B-Chat");
    }

    #[test]
    fn config_model_id_fallback() {
        let config = CandleConfig::new("/");
        // Root path has no filename component
        assert_eq!(config.model_id, "candle-model");
    }

    // ---- Prompt formatting tests ----

    #[test]
    fn format_prompt_simple() {
        let messages = vec![
            ChatMessage::system("You are helpful."),
            ChatMessage::user("Hello"),
        ];
        let prompt = format_prompt(&messages, None);
        assert!(prompt.contains("<|im_start|>system\nYou are helpful.<|im_end|>"));
        assert!(prompt.contains("<|im_start|>user\nHello<|im_end|>"));
        assert!(prompt.ends_with("<|im_start|>assistant\n"));
    }

    #[test]
    fn format_prompt_multi_turn() {
        let messages = vec![
            ChatMessage::system("Be concise."),
            ChatMessage::user("What is Rust?"),
            ChatMessage::assistant("A systems language."),
            ChatMessage::user("Tell me more."),
        ];
        let prompt = format_prompt(&messages, None);
        assert!(prompt.contains("What is Rust?"));
        assert!(prompt.contains("A systems language."));
        assert!(prompt.contains("Tell me more."));
        assert!(prompt.ends_with("<|im_start|>assistant\n"));
    }

    #[test]
    fn format_prompt_empty_messages() {
        let messages: Vec<ChatMessage> = vec![];
        let prompt = format_prompt(&messages, None);
        assert_eq!(prompt, "<|im_start|>assistant\n");
    }

    #[test]
    fn format_prompt_with_tools() {
        let tools = vec![Tool::function(
            "get_weather",
            "Get weather for a location",
            serde_json::json!({
                "type": "object",
                "properties": {
                    "location": {"type": "string"}
                }
            }),
        )];
        let messages = vec![
            ChatMessage::system("You are helpful."),
            ChatMessage::user("What is the weather?"),
        ];
        let prompt = format_prompt(&messages, Some(&tools));
        assert!(prompt.contains("You have access to the following tools:"));
        assert!(prompt.contains("get_weather"));
        assert!(prompt.contains("tool_calls"));
        // System message content should be present
        assert!(prompt.contains("You are helpful."));
        // Should NOT have a duplicate system block from regular formatting
        let system_count = prompt.matches("<|im_start|>system").count();
        assert_eq!(system_count, 1);
    }

    #[test]
    fn format_prompt_with_empty_tools() {
        let tools: Vec<Tool> = vec![];
        let messages = vec![ChatMessage::user("Hello")];
        let prompt = format_prompt(&messages, Some(&tools));
        // Empty tools should format like no tools at all
        assert!(!prompt.contains("You have access to the following tools:"));
        assert!(prompt.contains("<|im_start|>user\nHello<|im_end|>"));
    }

    // ---- Tool call parsing tests ----

    #[test]
    fn parse_tool_calls_full_format() {
        let text = r#"{"tool_calls": [{"id": "call_123", "type": "function", "function": {"name": "get_weather", "arguments": "{\"location\": \"NYC\"}"}}]}"#;
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].id, "call_123");
        assert_eq!(calls[0].function.name, "get_weather");
        assert!(calls[0].function.arguments.contains("NYC"));
    }

    #[test]
    fn parse_tool_calls_simple_format() {
        let text = r#"{"name": "search", "arguments": {"query": "rust programming"}}"#;
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "search");
        assert!(calls[0].function.arguments.contains("rust programming"));
    }

    #[test]
    fn parse_tool_calls_with_markdown_wrapper() {
        let text = "Sure, let me look that up:\n```json\n{\"tool_calls\": [{\"id\": \"call_1\", \"type\": \"function\", \"function\": {\"name\": \"search\", \"arguments\": \"{}\"}}]}\n```\n";
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "search");
    }

    #[test]
    fn parse_tool_calls_with_surrounding_text() {
        let text = "I'll call the weather function: {\"name\": \"get_weather\", \"arguments\": {\"city\": \"London\"}} to check.";
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].function.name, "get_weather");
    }

    #[test]
    fn parse_tool_calls_no_json() {
        let text = "I don't need to call any tools for this. The answer is 42.";
        assert!(parse_tool_calls(text).is_none());
    }

    #[test]
    fn parse_tool_calls_invalid_json() {
        let text = "{this is not valid json}";
        assert!(parse_tool_calls(text).is_none());
    }

    #[test]
    fn parse_tool_calls_json_but_no_tool_structure() {
        let text = r#"{"answer": "The result is 42"}"#;
        assert!(parse_tool_calls(text).is_none());
    }

    #[test]
    fn parse_tool_calls_multiple_tools() {
        let text = r#"{"tool_calls": [
            {"id": "call_1", "type": "function", "function": {"name": "search", "arguments": "{\"q\": \"a\"}"}},
            {"id": "call_2", "type": "function", "function": {"name": "calculate", "arguments": "{\"expr\": \"1+1\"}"}}
        ]}"#;
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].function.name, "search");
        assert_eq!(calls[1].function.name, "calculate");
    }

    #[test]
    fn parse_tool_calls_arguments_as_object() {
        // Some models emit arguments as a JSON object rather than a string
        let text = r#"{"name": "fetch", "arguments": {"url": "https://example.com"}}"#;
        let calls = parse_tool_calls(text).unwrap();
        assert_eq!(calls[0].function.name, "fetch");
        // Arguments should be serialized to string
        let args: serde_json::Value =
            serde_json::from_str(&calls[0].function.arguments).unwrap();
        assert_eq!(args["url"], "https://example.com");
    }

    // ---- JSON extraction tests ----

    #[test]
    fn extract_json_block_code_fence() {
        let text = "Here:\n```json\n{\"a\": 1}\n```\nDone.";
        assert_eq!(extract_json_block(text), Some("{\"a\": 1}"));
    }

    #[test]
    fn extract_json_block_bare_code_fence() {
        let text = "Result:\n```\n{\"b\": 2}\n```";
        assert_eq!(extract_json_block(text), Some("{\"b\": 2}"));
    }

    #[test]
    fn extract_json_block_inline() {
        let text = "The result is {\"c\": 3} here.";
        assert_eq!(extract_json_block(text), Some("{\"c\": 3}"));
    }

    #[test]
    fn extract_json_block_nested() {
        let text = r#"Result: {"outer": {"inner": 1}}"#;
        assert_eq!(
            extract_json_block(text),
            Some(r#"{"outer": {"inner": 1}}"#)
        );
    }

    #[test]
    fn extract_json_block_no_json() {
        let text = "No JSON here at all.";
        assert!(extract_json_block(text).is_none());
    }

    // ---- Stop token tests ----

    #[test]
    fn is_stop_token_matches_eos() {
        assert!(is_stop_token(2, Some(2), None));
        assert!(is_stop_token(2, Some(2), Some(5)));
    }

    #[test]
    fn is_stop_token_matches_im_end() {
        assert!(is_stop_token(5, None, Some(5)));
        assert!(is_stop_token(5, Some(2), Some(5)));
    }

    #[test]
    fn is_stop_token_no_match() {
        assert!(!is_stop_token(3, Some(2), Some(5)));
        assert!(!is_stop_token(3, None, None));
    }

    // ---- Clean streaming token tests ----

    #[test]
    fn clean_streaming_token_normal() {
        assert_eq!(clean_streaming_token("hello"), "hello");
        assert_eq!(clean_streaming_token(" world"), " world");
    }

    #[test]
    fn clean_streaming_token_special() {
        assert_eq!(clean_streaming_token("<|im_end|>"), "");
        assert_eq!(clean_streaming_token("<|endoftext|>"), "");
        assert_eq!(clean_streaming_token("</s>"), "");
        assert_eq!(clean_streaming_token("<|im_start|>"), "");
    }

    #[test]
    fn clean_streaming_token_embedded_special() {
        // If special token is embedded in other text, still filter
        assert_eq!(clean_streaming_token("text<|im_end|>more"), "");
    }

    // ---- Decode and clean tests ----

    #[test]
    fn decode_and_clean_strips_artifacts() {
        // We can't use a real tokenizer here, but we test the clean logic
        let text = "Hello world<|im_end|>";
        let cleaned = text
            .trim()
            .trim_end_matches("<|im_end|>")
            .trim_end_matches("<|endoftext|>")
            .trim_end_matches("</s>")
            .trim_end_matches("<|eot_id|>")
            .trim();
        assert_eq!(cleaned, "Hello world");
    }

    #[test]
    fn decode_and_clean_multiple_artifacts() {
        let text = "  Response here </s> ";
        let cleaned = text
            .trim()
            .trim_end_matches("<|im_end|>")
            .trim_end_matches("<|endoftext|>")
            .trim_end_matches("</s>")
            .trim_end_matches("<|eot_id|>")
            .trim();
        assert_eq!(cleaned, "Response here");
    }
}